version: '3.8'
services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
    depends_on:
      - pgsql

  pgsql:
    image: postgres:13
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgsql_data:
